"""
ISNE Training Orchestrator.

This module provides the orchestration logic for training the ISNE model using document
embeddings and relationships generated by the document processing pipeline. It handles
the complete training workflow from data loading to model evaluation and persistence.
"""

import os
import sys
import json
import time
import logging
import argparse
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any, Optional, Union, Tuple, Set, cast

import torch
import torch.nn as nn
import torch.optim as optim
from torch import Tensor
import numpy as np
from torch_geometric.data import Data, Dataset
from torch_geometric.utils import add_self_loops, to_undirected
from tqdm import tqdm

# Import ISNE components
from src.isne.models.isne_model import ISNEModel
from src.isne.training.trainer import ISNETrainer

from typing import cast, List, Any, Union, Dict, TypedDict, Optional

# Import centralized type definitions
from src.types.isne import (
    ISNEConfig,
    ISNEModelConfig,
    ISNETrainingConfig,
    ISNEGraphConfig,
    ISNEDirectoriesConfig,
    DocumentType,
    RelationType,
    IngestDocument,
    DocumentRelation
)

# Import configuration utilities
try:
    from src.config.config_loader import load_pipeline_config
    CONFIG_LOADER_AVAILABLE = True
except ImportError:
    CONFIG_LOADER_AVAILABLE = False

# Configure logging
logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)


class ISNETrainingOrchestrator:
    """
    Orchestrates the complete ISNE model training workflow.
    
    This class handles the process of taking processed documents from the document
    pipeline, constructing a graph representation, training the ISNE model on this
    graph, evaluating model performance, and persisting the trained model.
    
    Attributes:
        input_dir: Directory containing processed documents from the pipeline
        output_dir: Directory for saving training artifacts
        model_output_dir: Directory for saving trained models
        self.config: Configuration settings for training
        device: Device to use for training (CPU or GPU)
    """
    
    def __init__(
        self,
        documents: Optional[List[Dict[str, Any]]] = None,
        input_dir: Optional[Union[str, Path]] = None,
        output_dir: Optional[Union[str, Path]] = None,
        model_output_dir: Optional[Union[str, Path]] = None,
        config_override: Optional[Dict[str, Any]] = None,
        device: Optional[str] = None,
        sampler_config: Optional[Dict[str, Any]] = None
    ):
        """
        Initialize the ISNE training orchestrator.
        
        Args:
            documents: Optional list of processed document objects with embeddings (in-memory).
                      If provided, input_dir is ignored and documents are used directly.
            input_dir: Directory containing processed documents (from pipeline_multiprocess_test).
                       Used only if documents parameter is None.
            output_dir: Directory for storing training artifacts and results.
                         If None, uses the directory from self.config.
            model_output_dir: Directory for saving trained models.
                              If None, uses the directory from self.config.
            config_override: Optional dictionary to override default configuration settings
            device: Training device (e.g., "cpu", "cuda:0"); if None, uses self.config setting
            sampler_config: Optional configuration for the sampler class to use during training.
                          Format: {"sampler_class": Class, "sampler_params": Dict[str, Any]}
        """
        # Store the documents passed directly in memory
        self.processed_documents = documents
        # Store custom sampler configuration if provided
        self.sampler_config = sampler_config
        # Load configuration first so we can use directory defaults
        self.config = cast(ISNEConfig, self._load_config())
        
        # Apply configuration overrides if provided
        if config_override:
            self._apply_config_override(config_override)
            
        # Get directory configuration
        dir_config = getattr(self.config, "isne", {}).get("directories", {}) if hasattr(self.config, "isne") else {}
        
        # Set directory paths, using config values as defaults
        if input_dir is None:
            default_input = getattr(dir_config, "input_dir", "./test-output/pipeline-mp-test") if hasattr(dir_config, "input_dir") else "./test-output/pipeline-mp-test"
            self.input_dir = Path(default_input)
        else:
            self.input_dir = Path(input_dir) if isinstance(input_dir, str) else input_dir
        
        if output_dir is None:
            default_output = getattr(dir_config, "output_dir", "./test-output/isne-training") if hasattr(dir_config, "output_dir") else "./test-output/isne-training"
            self.output_dir = Path(default_output)
        else:
            self.output_dir = Path(output_dir) if isinstance(output_dir, str) else output_dir
        
        if model_output_dir is None:
            default_model_dir = getattr(dir_config, "model_dir", "./models/isne") if hasattr(dir_config, "model_dir") else "./models/isne"
            self.model_output_dir = Path(default_model_dir)
        else:
            self.model_output_dir = Path(model_output_dir) if isinstance(model_output_dir, str) else model_output_dir
            
        # Set device based on configuration or explicit parameter
        if device is not None:
            self.device = device
        else:
            # Check global CPU/GPU execution settings first
            if "gpu_execution" in self.config and getattr(self.config, "gpu_execution", {}).get("enabled", False):
                # Use GPU settings
                self.device = getattr(self.config, "gpu_execution", {}).get("device", "cuda:0")
                logger.info(f"Using GPU execution mode with device: {self.device}")
            elif "cpu_execution" in self.config and getattr(self.config, "cpu_execution", {}).get("enabled", False):
                # Use CPU settings
                self.device = "cpu"
                logger.info("Using CPU execution mode")
            else:
                # Fall back to ISNE-specific device setting
                # Fix the nested dictionary access with proper type checking
                if hasattr(self.config, "isne"):
                    isne_config = getattr(self.config, "isne", {})
                    training_config = isne_config.get("training", {}) if isinstance(isne_config, dict) else {}
                    device_config = training_config.get("device", "cpu") if isinstance(training_config, dict) else "cpu"
                else:
                    device_config = "cpu"
                
                # Ensure device_config is a string
                self.device = str(device_config)
                logger.info(f"Using ISNE-specific device setting: {self.device}")
        
        # Create directories if they don't exist
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.model_output_dir.mkdir(parents=True, exist_ok=True)
        
        logger.info(f"ISNE Training Orchestrator initialized:")
        if self.processed_documents:
            logger.info(f"  Using {len(self.processed_documents)} documents provided directly in memory")
        elif self.input_dir:
            logger.info(f"  Input directory: {self.input_dir}")
        logger.info(f"  Output directory: {self.output_dir}")
        logger.info(f"  Model output directory: {self.model_output_dir}")
        logger.info(f"  Training device: {self.device}")
        
        # Initialize training metrics
        self.training_metrics: Dict[str, Any] = {
            "start_time": None,
            "end_time": None,
            "duration": None,
            "epochs": 0,
            "losses": [],
            "validation_metrics": []
        }
        
        # Initialize trainer and graph data
        self.trainer: Optional[ISNETrainer] = None
        self.graph_data: Optional[Any] = None
    
    def _load_config(self) -> ISNEConfig:
        """
        Load configuration settings for ISNE training from the training pipeline self.config.
        
        Returns:
            Configuration dictionary containing ISNE settings
        """
        # Initialize with empty config of the correct type
        isne_config: ISNEConfig = {
            "model": {},
            "training": {},
            "graph": {},
            "directories": {}
        }
        
        # Try to use config_loader if available
        if CONFIG_LOADER_AVAILABLE:
            try:
                # Load the unified training pipeline configuration
                pipeline_config = load_pipeline_config(pipeline_type="training")
                logger.info("Loaded configuration using config_loader")
                
                # Store the pipeline config but cast it as Any to avoid type errors
                # We'll properly type our isne_config which will be returned
                self.config = cast(Any, pipeline_config)
                
                # Check if ISNE configuration exists in the loaded config
                if hasattr(pipeline_config, "isne") and isinstance(pipeline_config.isne, dict):
                    # Extract ISNE-specific configuration
                    pipeline_isne_config = pipeline_config.isne
                    
                    # Update our typed config dictionary with values from pipeline config
                    # Only use keys that are valid for ISNEConfig TypedDict
                    # Handle each section individually with proper typing for each field
                    if "model" in pipeline_isne_config and isinstance(pipeline_isne_config["model"], dict):
                        model_dict = pipeline_isne_config["model"]
                        # Explicitly check and assign each key with a string literal
                        if "embedding_dim" in model_dict:
                            isne_config["model"]["embedding_dim"] = model_dict["embedding_dim"]
                        if "hidden_dim" in model_dict:
                            isne_config["model"]["hidden_dim"] = model_dict["hidden_dim"]
                        if "output_dim" in model_dict:
                            isne_config["model"]["output_dim"] = model_dict["output_dim"]
                        if "num_layers" in model_dict:
                            isne_config["model"]["num_layers"] = model_dict["num_layers"]
                        if "num_heads" in model_dict:
                            isne_config["model"]["num_heads"] = model_dict["num_heads"]
                        if "dropout" in model_dict:
                            isne_config["model"]["dropout"] = model_dict["dropout"]
                        if "activation" in model_dict:
                            isne_config["model"]["activation"] = model_dict["activation"]
                        if "add_self_loops" in model_dict:
                            isne_config["model"]["add_self_loops"] = model_dict["add_self_loops"]
                    
                    if "training" in pipeline_isne_config and isinstance(pipeline_isne_config["training"], dict):
                        train_dict = pipeline_isne_config["training"]
                        # Explicitly check and assign each key with a string literal
                        if "learning_rate" in train_dict:
                            isne_config["training"]["learning_rate"] = train_dict["learning_rate"]
                        if "weight_decay" in train_dict:
                            isne_config["training"]["weight_decay"] = train_dict["weight_decay"]
                        if "batch_size" in train_dict:
                            isne_config["training"]["batch_size"] = train_dict["batch_size"]
                        if "epochs" in train_dict:
                            isne_config["training"]["epochs"] = train_dict["epochs"]
                        if "num_hops" in train_dict:
                            isne_config["training"]["num_hops"] = train_dict["num_hops"]
                        if "neighbor_size" in train_dict:
                            isne_config["training"]["neighbor_size"] = train_dict["neighbor_size"]
                        if "eval_interval" in train_dict:
                            isne_config["training"]["eval_interval"] = train_dict["eval_interval"]
                        if "early_stopping_patience" in train_dict:
                            isne_config["training"]["early_stopping_patience"] = train_dict["early_stopping_patience"]
                        if "checkpoint_interval" in train_dict:
                            isne_config["training"]["checkpoint_interval"] = train_dict["checkpoint_interval"]
                        if "device" in train_dict:
                            isne_config["training"]["device"] = train_dict["device"]
                        if "lambda_feat" in train_dict:
                            isne_config["training"]["lambda_feat"] = train_dict["lambda_feat"]
                        if "lambda_struct" in train_dict:
                            isne_config["training"]["lambda_struct"] = train_dict["lambda_struct"]
                        if "lambda_contrast" in train_dict:
                            isne_config["training"]["lambda_contrast"] = train_dict["lambda_contrast"]
                    
                    if "graph" in pipeline_isne_config and isinstance(pipeline_isne_config["graph"], dict):
                        graph_dict = pipeline_isne_config["graph"]
                        # Explicitly check and assign each key with a string literal
                        if "similarity_threshold" in graph_dict:
                            isne_config["graph"]["similarity_threshold"] = graph_dict["similarity_threshold"]
                        if "max_neighbors" in graph_dict:
                            isne_config["graph"]["max_neighbors"] = graph_dict["max_neighbors"]
                        if "sequential_weight" in graph_dict:
                            isne_config["graph"]["sequential_weight"] = graph_dict["sequential_weight"]
                        if "similarity_weight" in graph_dict:
                            isne_config["graph"]["similarity_weight"] = graph_dict["similarity_weight"]
                        if "window_size" in graph_dict:
                            isne_config["graph"]["window_size"] = graph_dict["window_size"]
                    
                    if "directories" in pipeline_isne_config and isinstance(pipeline_isne_config["directories"], dict):
                        dir_dict = pipeline_isne_config["directories"]
                        # Explicitly check and assign each key with a string literal
                        if "data_dir" in dir_dict:
                            isne_config["directories"]["data_dir"] = dir_dict["data_dir"]
                        if "input_dir" in dir_dict:
                            isne_config["directories"]["input_dir"] = dir_dict["input_dir"]
                        if "output_dir" in dir_dict:
                            isne_config["directories"]["output_dir"] = dir_dict["output_dir"]
                        if "model_dir" in dir_dict:
                            isne_config["directories"]["model_dir"] = dir_dict["model_dir"]
                
                # Set default values for model configuration
                if "model" not in isne_config:
                    isne_config["model"] = {}
                model_config = isne_config["model"]
                model_config.setdefault("embedding_dim", 768)
                model_config.setdefault("hidden_dim", 256)
                model_config.setdefault("output_dim", 768)
                model_config.setdefault("num_layers", 2)
                model_config.setdefault("num_heads", 8)
                model_config.setdefault("dropout", 0.1)
                model_config.setdefault("activation", "elu")
                model_config.setdefault("add_self_loops", True)
                
                # Set default values for training configuration
                if "training" not in isne_config:
                    isne_config["training"] = {}
                training_config = isne_config["training"]
                training_config.setdefault("learning_rate", 0.001)
                training_config.setdefault("weight_decay", 1e-5)
                training_config.setdefault("epochs", 50)
                training_config.setdefault("batch_size", 32)
                training_config.setdefault("num_hops", 1)
                training_config.setdefault("neighbor_size", 10)
                training_config.setdefault("eval_interval", 5)
                training_config.setdefault("early_stopping_patience", 10)
                training_config.setdefault("checkpoint_interval", 5)
                training_config.setdefault("device", "cpu")
                training_config.setdefault("lambda_feat", 1.0)
                training_config.setdefault("lambda_struct", 1.0)
                training_config.setdefault("lambda_contrast", 0.5)
                
                # Set default values for graph construction
                if "graph" not in isne_config:
                    isne_config["graph"] = {}
                graph_config = isne_config["graph"]
                graph_config.setdefault("similarity_threshold", 0.7)
                graph_config.setdefault("max_neighbors", 5)
                graph_config.setdefault("sequential_weight", 0.9)
                graph_config.setdefault("similarity_weight", 0.7)
                graph_config.setdefault("window_size", 3)
                
                # Set default values for directories
                if "directories" not in isne_config:
                    isne_config["directories"] = {}
                dir_config = isne_config["directories"]
                dir_config.setdefault("data_dir", "./data/isne")
                dir_config.setdefault("input_dir", "./test-output/pipeline-mp-test")
                dir_config.setdefault("output_dir", "./test-output/isne-training")
                dir_config.setdefault("model_dir", "./models/isne")
                
                return isne_config
            except Exception as e:
                logger.warning(f"Error loading configuration with config_loader: {e}")
                logger.warning("Falling back to default configuration")
        
        # Fall back to default configuration
        logger.info("Using default ISNE training configuration")
        # Return a properly typed ISNEConfig object
        return {
            "model": {
                "embedding_dim": 768,
                "hidden_dim": 256,
                "output_dim": 768,
                "num_layers": 2,
                "num_heads": 8,
                "dropout": 0.1,
                "activation": "elu",
                "add_self_loops": True
            },
            "training": {
                "learning_rate": 0.001,
                "weight_decay": 1e-5,
                "epochs": 50,
                "batch_size": 32,
                "num_hops": 1,
                "neighbor_size": 10,
                "eval_interval": 5,
                "early_stopping_patience": 10,
                "checkpoint_interval": 5,
                "device": "cpu",
                "lambda_feat": 1.0,
                "lambda_struct": 1.0,
                "lambda_contrast": 0.5
            },
            "graph": {
                "similarity_threshold": 0.7,
                "max_neighbors": 5,
                "sequential_weight": 0.9,
                "similarity_weight": 0.7,
                "window_size": 3
            },
            "directories": {
                "data_dir": "./data/isne",
                "input_dir": "./test-output/pipeline-mp-test",
                "output_dir": "./test-output/isne-training",
                "model_dir": "./models/isne"
            }
        }
    
    def _apply_config_override(self, override: Dict[str, Any]) -> None:
        """
        Apply configuration overrides to the current configuration.
        
        Args:
            override: Dictionary with configuration overrides
        """
        # Handle fully nested structure (isne.section.parameter)
        if "isne" in override:
            isne_override = override["isne"]
            for section_name, section_values in isne_override.items():
                # Create section if it doesn't exist
                if section_name not in getattr(self.config, "isne", {}):
                    getattr(self.config, "isne", {})[section_name] = {}
                    
                # Apply section overrides
                for key, value in section_values.items():
                    getattr(self.config, "isne", {})[section_name][key] = value
                    
            logger.info(f"Applied nested configuration overrides to sections: {list(isne_override.keys())}")
        
        # Handle partially nested overrides (section.parameter) - these go to isne.section.parameter
        elif any(section in override for section in ["model", "training", "graph", "directories"]):
            for section_name in ["model", "training", "graph", "directories"]:
                if section_name in override:
                    # Create section if it doesn't exist
                    if section_name not in getattr(self.config, "isne", {}):
                        getattr(self.config, "isne", {})[section_name] = {}
                        
                    # Apply overrides to this section
                    for key, value in override[section_name].items():
                        getattr(self.config, "isne", {})[section_name][key] = value
                        
            logger.info("Applied section-level configuration overrides")
        
        # Handle flat overrides (parameter) - these go to isne.training.parameter for backward compatibility
        else:
            for key, value in override.items():
                getattr(self.config, "isne", {})["training"][key] = value
            
            logger.info("Applied flat configuration overrides to training section")
        
        logger.info("Configuration override completed")
    
    def _load_processed_documents(self) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
        """
        Load processed documents with embeddings from in-memory objects or from the input directory.
        
        Returns:
            Tuple of (processed_documents, pipeline_stats)
        """
        # If documents were provided directly in memory, use those
        if self.processed_documents is not None:
            logger.info(f"Using {len(self.processed_documents)} documents provided directly in memory")
            pipeline_stats = {
                "total_files": len(self.processed_documents),
                "processing_time": {},
                "file_details": {}
            }
            return self.processed_documents, pipeline_stats
        
        # Otherwise load from files (fallback method)
        # Check if input directory exists
        if not self.input_dir or not self.input_dir.exists():
            raise ValueError(f"Input directory not found: {self.input_dir}")
        
        # Define paths to load
        isne_input_path = self.input_dir / "isne_input_sample.json"
        stats_path = self.input_dir / "pipeline_stats.json"
        
        # Validate input files existence
        if not isne_input_path.exists():
            raise ValueError(f"ISNE input file not found: {isne_input_path}")
        
        # Load processed documents
        with open(isne_input_path, "r") as f:
            processed_documents = json.load(f)
        
        # Load pipeline stats if available, or create empty stats dict
        if not stats_path.exists():
            logger.warning(f"Pipeline stats file not found, using empty stats: {stats_path}")
            pipeline_stats = {
                "total_files": len(processed_documents),
                "processing_time": {},
                "file_details": {}
            }
        else:
            with open(stats_path, "r") as f:
                pipeline_stats = json.load(f)
        
        logger.info(f"Loaded {len(processed_documents)} processed documents from {isne_input_path}")
        
        return processed_documents, pipeline_stats
    
    def _construct_graph(self, documents: List[Dict[str, Any]]) -> Data:
        """
        Construct a graph from the processed documents based on configuration.
        
        Args:
            documents: List of processed documents with chunks and embeddings
            
        Returns:
            PyTorch Geometric Data dict representing the document graph
        """
        logger.info("Constructing document graph for ISNE training...")
        
        # Get graph construction parameters from typed config
        # Access config in a type-safe way, avoiding dict.get() method with empty dict as default
        if hasattr(self.config, "isne") and isinstance(getattr(self.config, "isne"), dict):
            isne_config = getattr(self.config, "isne")
            # Use a conditional to check for the key instead of the get() method
            if isinstance(isne_config, dict) and "graph" in isne_config:
                graph_config_dict = isne_config["graph"]
            else:
                graph_config_dict = {}
        else:
            graph_config_dict = {}
            
        # Create a properly typed ISNEGraphConfig with default values
        graph_config: ISNEGraphConfig = {
            "similarity_threshold": 0.7,
            "max_neighbors": 5,
            "sequential_weight": 0.9,
            "similarity_weight": 0.7,
            "window_size": 3
        }
        
        # Update the typed config with values from the loaded config
        # Use string literals for the keys to satisfy mypy's TypedDict requirements
        if isinstance(graph_config_dict, dict):
            if "similarity_threshold" in graph_config_dict:
                graph_config["similarity_threshold"] = graph_config_dict["similarity_threshold"]
            if "max_neighbors" in graph_config_dict:
                graph_config["max_neighbors"] = graph_config_dict["max_neighbors"]
            if "sequential_weight" in graph_config_dict:
                graph_config["sequential_weight"] = graph_config_dict["sequential_weight"]
            if "similarity_weight" in graph_config_dict:
                graph_config["similarity_weight"] = graph_config_dict["similarity_weight"]
            if "window_size" in graph_config_dict:
                graph_config["window_size"] = graph_config_dict["window_size"]
        
        # Access values directly from the properly typed dictionary using string literals
        # Since we've properly initialized graph_config with defaults, we can access fields directly
        similarity_threshold = graph_config["similarity_threshold"]
        max_neighbors = graph_config["max_neighbors"]
        sequential_weight = graph_config["sequential_weight"]
        similarity_weight = graph_config["similarity_weight"]
        window_size = graph_config["window_size"]
        
        # Collect chunk embeddings and IDs
        node_features = []
        node_ids = []
        id_to_index = {}  # Maps chunk ID to its index in the node list
        
        # Create nodes for each chunk with embeddings
        for doc in documents:
            for chunk in getattr(doc, "chunks", []) if hasattr(doc, "chunks") else []:
                # Handle chunks without embeddings
                if not chunk.get("embedding"):
                    # For testing purposes: generate random embeddings when none are found
                    # Use a safer approach to check if embedding_dim is available
                    embedding_dim = None
                    if hasattr(self.config, "isne"):
                        isne_config = getattr(self.config, "isne")
                        if isinstance(isne_config, dict) and "model" in isne_config:
                            model_config = isne_config["model"]
                            if isinstance(model_config, dict) and "embedding_dim" in model_config:
                                embedding_dim = model_config["embedding_dim"]
                    
                    # Only proceed if we found a valid embedding_dim
                    if embedding_dim is not None:
                        # Use deterministic seed based on chunk id for reproducibility
                        # Ensure embedding_dim is an integer before using it with np.random.normal
                        seed = int(hash(chunk["id"]) % 10000000)
                        np.random.seed(seed)
                        # Cast embedding_dim to int to avoid potential type errors
                        embedding_dim_int = int(embedding_dim)
                        random_embedding = np.random.normal(0, 0.1, embedding_dim_int).tolist()
                        chunk["embedding"] = random_embedding
                        logger.info(f"Generated random embedding for chunk {chunk['id']} (test mode)")
                    else:
                        # Skip if we can't determine embedding dimension
                        logger.warning(f"Skipping chunk without embedding: {chunk['id']}")
                        continue
                
                # Add to node list
                chunk_id = chunk["id"]
                node_ids.append(chunk_id)
                id_to_index[chunk_id] = len(node_ids) - 1
                
                # Convert embedding to tensor if it's a list
                embedding = chunk["embedding"]
                if isinstance(embedding, list):
                    embedding = torch.tensor(embedding, dtype=torch.float)
                
                node_features.append(embedding)
        
        # Check if we have nodes
        if not node_features:
            raise ValueError("No valid chunks with embeddings found in processed documents")
        
        # Log node count for debugging
        logger.info(f"Graph construction: collected {len(node_features)} nodes with embeddings")
        
        # Check for dimension consistency before stacking
        dim_counts = {}
        for i, feat in enumerate(node_features):
            dim = feat.shape[0] if hasattr(feat, 'shape') else len(feat)
            if dim not in dim_counts:
                dim_counts[dim] = 0
            dim_counts[dim] += 1
                
        if len(dim_counts) > 1:
            logger.warning(f"Inconsistent embedding dimensions detected: {dim_counts}")
            # Find the most common dimension
            most_common_dim = max(dim_counts.items(), key=lambda x: x[1])[0]
            logger.warning(f"Using most common dimension: {most_common_dim}")
            
            # Filter to keep only embeddings with the most common dimension
            valid_indices = []
            valid_features = []
            valid_ids = []
            
            for i, feat in enumerate(node_features):
                dim = feat.shape[0] if hasattr(feat, 'shape') else len(feat)
                if dim == most_common_dim:
                    valid_features.append(feat)
                    valid_ids.append(node_ids[i])
                    valid_indices.append(i)
            
            # Rebuild the id_to_index mapping with new contiguous indices
            id_to_index = {node_id: idx for idx, node_id in enumerate(valid_ids)}
            node_features = valid_features
            node_ids = valid_ids
            
            logger.info(f"Filtered to {len(node_features)} nodes with consistent dimension {most_common_dim}")
        
        # Stack node features into a single tensor
        node_features_tensor = torch.stack(node_features)
        
        # Create edges based on document structure, directory hierarchy, and semantic similarity
        edge_list = []
        edge_weights = []
        
        # Track document to directory mapping if available
        doc_to_directory = {}
        # Try to extract directory information from document paths
        for doc in documents:
            if "source" in doc and isinstance(doc["source"], str):
                source_path = Path(doc["source"])
                doc_to_directory[doc["file_id"]] = str(source_path.parent)
            elif "file_path" in doc and isinstance(doc["file_path"], str):
                file_path = Path(doc["file_path"])
                doc_to_directory[doc["file_id"]] = str(file_path.parent)
        
        # Track edges statistics
        edge_stats = {
            "attempted": 0,  # Total attempted edges
            "added": 0,     # Successfully added edges
            "invalid_id": 0,  # Edges with invalid IDs
            "self_loops": 0,  # Self-loop edges
            "duplicate": 0,   # Duplicate edges
        }
        
        # Set to track existing edges to avoid duplicates
        existing_edges = set()
        
        # Helper function to add an edge with validation
        def add_edge(src_id: str, dst_id: str, weight: float = 1.0) -> bool:
            edge_stats["attempted"] += 1
            
            # Validate IDs exist in our mapping
            if src_id not in id_to_index:
                edge_stats["invalid_id"] += 1
                return False
                
            if dst_id not in id_to_index:
                edge_stats["invalid_id"] += 1
                return False
            
            # Get indices
            src_idx = id_to_index[src_id]
            dst_idx = id_to_index[dst_id]
            
            # Avoid self-loops
            if src_idx == dst_idx:
                edge_stats["self_loops"] += 1
                return False
            
            # Check for duplicates
            edge_key = (src_idx, dst_idx)
            if edge_key in existing_edges:
                edge_stats["duplicate"] += 1
                return False
            
            # Add the edge
            edge_list.append([src_idx, dst_idx])
            edge_weights.append(weight)
            existing_edges.add(edge_key)
            edge_stats["added"] += 1
            return True
        
        # Add sequential edges within documents
        for doc in documents:
            chunks = getattr(doc, "chunks", []) if hasattr(doc, "chunks") else []
            for i in range(len(chunks) - 1):
                # Sequential connection with weight from config
                add_edge(chunks[i]["id"], chunks[i+1]["id"], weight=sequential_weight)
        
        # Add directory-based relationships if directory structure is available
        directory_relationship_weight = getattr(graph_config, "directory_relationship_weight", 0.5) if hasattr(graph_config, "directory_relationship_weight") else 0.5
        
        # Group documents by directory
        docs_by_directory: Dict[str, List[str]] = {}
        for doc_id, directory in doc_to_directory.items():
            if directory not in docs_by_directory:
                docs_by_directory[directory] = []
            docs_by_directory[directory].append(doc_id)
        
        # Connect documents in the same directory
        if directory_relationship_weight > 0 and docs_by_directory:
            logger.info(f"Adding directory-based relationships with weight {directory_relationship_weight}")
            
            for directory, doc_ids in docs_by_directory.items():
                if len(doc_ids) > 1:  # Only if multiple documents in same directory
                    logger.info(f"Creating relationships between {len(doc_ids)} documents in directory: {directory}")
                    
                    # Create mapping of document ID to chunks
                    doc_to_chunks = {}
                    for doc in documents:
                        doc_id = getattr(doc, "file_id", getattr(doc, "id", "")) if hasattr(doc, "get") else getattr(doc, "id", None)
                        if doc_id in doc_ids:
                            if hasattr(doc, "chunks"):
                                doc_to_chunks[doc_id] = [chunk["id"] for chunk in getattr(doc, "chunks", [])]
                            else:
                                doc_to_chunks[doc_id] = []
                    
                    # Connect first chunks of documents in the same directory
                    for i, doc1_id in enumerate(doc_ids):
                        if doc1_id not in doc_to_chunks or not doc_to_chunks[doc1_id]:
                            continue
                            
                        for j in range(i+1, len(doc_ids)):
                            doc2_id = doc_ids[j]
                            if doc2_id not in doc_to_chunks or not doc_to_chunks[doc2_id]:
                                continue
                                
                            # Connect first chunk of each document
                            src_id = doc_to_chunks[doc1_id][0]
                            dst_id = doc_to_chunks[doc2_id][0]
                            add_edge(src_id, dst_id, directory_relationship_weight)
        
        # Add edges for semantically similar chunks based on overlap context
        for doc in documents:
            chunks = getattr(doc, "chunks", []) if hasattr(doc, "chunks") else []
            for i, chunk in enumerate(chunks):
                if "overlap_context" in chunk:
                    # If there are previous/next chunks indicated in overlap context, connect them
                    if "position" in chunk["overlap_context"] and "total" in chunk["overlap_context"]:
                        pos = chunk["overlap_context"]["position"]
                        total = chunk["overlap_context"]["total"]
                        
                        # Connect to neighboring chunks within a window defined by config
                        for j in range(max(0, i-window_size), min(len(chunks), i+window_size+1)):
                            if i != j:  # Skip self
                                # Weight based on proximity and config similarity weight
                                proximity_factor = 1.0 - (abs(i-j) / (window_size+1))
                                edge_weight = similarity_weight * proximity_factor
                                add_edge(chunk["id"], chunks[j]["id"], weight=edge_weight)
        
        # Convert edge list to tensor
        if not edge_list:
            raise ValueError("No edges created in the document graph")
        
        edge_index = torch.tensor(edge_list, dtype=torch.long).t().contiguous()
        edge_attr = torch.tensor(edge_weights, dtype=torch.float)
        
        # Make graph undirected
        edge_index, edge_attr = to_undirected(edge_index, edge_attr)
        
        # Log edge statistics before finalizing
        logger.info(f"Edge construction statistics:")
        logger.info(f"  Attempted: {edge_stats['attempted']}")
        logger.info(f"  Added: {edge_stats['added']} ({edge_stats['added']/max(1, edge_stats['attempted'])*100:.1f}%)")
        logger.info(f"  Invalid IDs: {edge_stats['invalid_id']}")
        logger.info(f"  Self-loops: {edge_stats['self_loops']}")
        logger.info(f"  Duplicates: {edge_stats['duplicate']}")
        
        # Check if we have any edges
        if not edge_list:
            logger.warning("No valid edges found in graph. Creating minimal fallback graph.")
            # Create minimal valid edges to avoid crashes
            num_nodes = len(node_ids)
            if num_nodes >= 2:
                # Create a simple path graph as fallback
                for i in range(num_nodes - 1):
                    edge_list.append([i, i+1])
                    edge_weights.append(1.0)
                logger.warning(f"Created {len(edge_list)} fallback edges as simple path graph")
            elif num_nodes == 1:
                # Create a self-loop as last resort
                edge_list.append([0, 0])
                edge_weights.append(1.0)
                logger.warning("Created single self-loop as fallback (only one node in graph)")
            else:
                raise ValueError("Cannot create graph with no nodes")
        
        # Validate edge indices before creating tensors
        num_nodes = len(node_features)
        valid_edges = []
        valid_weights = []
        invalid_count = 0
        
        for i, (src, dst) in enumerate(edge_list):
            if 0 <= src < num_nodes and 0 <= dst < num_nodes:
                valid_edges.append([src, dst])
                valid_weights.append(edge_weights[i])
            else:
                invalid_count += 1
        
        if invalid_count > 0:
            logger.warning(f"Filtered {invalid_count} edges with invalid indices")
            
        if not valid_edges:
            logger.error("No valid edges remaining after final validation")
            # Create minimal valid graph as last resort
            for i in range(min(num_nodes - 1, 10)):
                valid_edges.append([i, i+1])
                valid_weights.append(1.0)
            logger.warning(f"Created {len(valid_edges)} last-resort edges")
                
        # Create edge index tensor with proper format (2 x num_edges)
        edge_index = torch.tensor(valid_edges, dtype=torch.long).t().contiguous()
        edge_attr = torch.tensor(valid_weights, dtype=torch.float).view(-1, 1)
        
        # Create graph using PyTorch Geometric Data
        data = Data(
            x=node_features_tensor,  # Node features tensor (stacked)
            edge_index=edge_index,  # Graph structure
            edge_attr=edge_attr  # Edge weights
        )
        
        # Add additional metadata
        data.node_ids = node_ids
        
        # Final validation of graph for consistency
        num_edges = data.num_edges
        logger.info(f"Constructed graph with {data.num_nodes} nodes and {num_edges} edges")
        logger.info(f"Edge index tensor shape: {data.edge_index.shape}")
        logger.info(f"Edge attributes tensor shape: {data.edge_attr.shape}")
        
        # Log max node index for debugging
        if num_edges > 0:
            max_src = data.edge_index[0].max().item()
            max_dst = data.edge_index[1].max().item()
            logger.info(f"Max node indices in edge index: src={max_src}, dst={max_dst}")
            
            # Final sanity check
            if max_src >= data.num_nodes or max_dst >= data.num_nodes:
                logger.error(f"Graph inconsistency detected: max index exceeds node count!")
        
        return data
    
    def _prepare_trainer(self) -> ISNETrainer:
        """
        Initialize and prepare the ISNE trainer using configuration settings.
        
        Returns:
            Initialized ISNETrainer instance
        """
        # Get model and training parameters from typed config
        model_config: ISNEModelConfig = getattr(self.config, "isne", {})["model"]
        train_config: ISNETrainingConfig = getattr(self.config, "isne", {})["training"]
        
        # Prepare arguments for the trainer
        trainer_args = {
            "embedding_dim": int(model_config["embedding_dim"]),
            "hidden_dim": int(model_config["hidden_dim"]),
            "output_dim": int(model_config["output_dim"]),
            "num_layers": int(model_config["num_layers"]),
            "num_heads": int(model_config["num_heads"]),
            "dropout": float(model_config["dropout"]),
            "learning_rate": float(train_config["learning_rate"]),
            "weight_decay": float(train_config["weight_decay"]),
            "lambda_feat": float(getattr(train_config, "lambda_feat", 1.0) if hasattr(train_config, "lambda_feat") else 1.0),
            "lambda_struct": float(getattr(train_config, "lambda_struct", 1.0) if hasattr(train_config, "lambda_struct") else 1.0),
            "lambda_contrast": float(getattr(train_config, "lambda_contrast", 0.5) if hasattr(train_config, "lambda_contrast") else 0.5),
            "device": self.device
        }
        
        # Check if custom sampler config was provided
        sampler_config_typed: Optional[Dict[str, Any]] = None
        if self.sampler_config:
            logger.info(f"Using custom sampler configuration with {self.sampler_config['sampler_class'].__name__}")
            sampler_config_typed = self.sampler_config
        trainer_args["sampler_config"] = sampler_config_typed
        
        # Extract parameters with proper types before passing them to ISNETrainer
        embedding_dim: int = int(str(trainer_args["embedding_dim"]))
        hidden_dim: int = int(str(trainer_args["hidden_dim"]))
        output_dim: Optional[int] = int(str(trainer_args["output_dim"])) if trainer_args.get("output_dim") is not None else None
        num_layers: int = int(str(trainer_args["num_layers"]))
        num_heads: int = int(str(trainer_args["num_heads"]))
        dropout: float = float(str(trainer_args["dropout"]))
        learning_rate: float = float(str(trainer_args["learning_rate"]))
        weight_decay: float = float(str(trainer_args["weight_decay"]))
        lambda_feat: float = float(str(trainer_args["lambda_feat"]))
        lambda_struct: float = float(str(trainer_args["lambda_struct"]))
        lambda_contrast: float = float(str(trainer_args["lambda_contrast"]))
        device_str: str = str(trainer_args["device"])
        sampler_config_obj: Optional[Dict[str, Any]] = sampler_config_typed
        
        # Initialize trainer with properly typed arguments
        self.trainer = ISNETrainer(
            embedding_dim=embedding_dim,
            hidden_dim=hidden_dim,
            output_dim=output_dim,
            num_layers=num_layers,
            num_heads=num_heads,
            dropout=dropout,
            learning_rate=learning_rate,
            weight_decay=weight_decay,
            lambda_feat=lambda_feat,
            lambda_struct=lambda_struct,
            lambda_contrast=lambda_contrast,
            device=device_str,
            sampler_config=sampler_config_obj
        )
        
        # Prepare the model, losses, and optimizer
        self.trainer.prepare_model()
        
        logger.info("Initialized ISNE trainer with configuration parameters")
        
        return self.trainer
    
    def train(self) -> Dict[str, Any]:
        """
        Execute the complete ISNE training workflow.
        
        Returns:
            Dictionary with training results and metrics
        """
        logger.info("Starting ISNE training workflow...")
        
        # Track overall training time
        self.training_metrics["start_time"] = time.time()
        
        # Load processed documents (either from memory or from files)
        documents, pipeline_stats = self._load_processed_documents()
        
        # Construct the document graph
        graph_data = self._construct_graph(documents)
        
        # Prepare trainer
        self._prepare_trainer()
        
        # Get training parameters from typed config using a safer approach
        # Create a default training config in case it's not available
        train_config: ISNETrainingConfig = {
            "learning_rate": 0.001,
            "weight_decay": 1e-5,
            "epochs": 50,
            "batch_size": 32,
            "num_hops": 1,
            "neighbor_size": 10,
            "eval_interval": 5,
            "early_stopping_patience": 10,
            "checkpoint_interval": 5,
            "device": "cpu",
            "lambda_feat": 1.0,
            "lambda_struct": 1.0,
            "lambda_contrast": 0.5
        }
        
        # Update with values from self.config if available
        if hasattr(self.config, "isne") and isinstance(getattr(self.config, "isne"), dict):
            isne_config = getattr(self.config, "isne")
            if isinstance(isne_config, dict) and "training" in isne_config and isinstance(isne_config["training"], dict):
                config_train = isne_config["training"]
                # Update with available values using explicit assignments with string literals
                if "learning_rate" in config_train:
                    train_config["learning_rate"] = config_train["learning_rate"]
                if "weight_decay" in config_train:
                    train_config["weight_decay"] = config_train["weight_decay"]
                if "epochs" in config_train:
                    train_config["epochs"] = config_train["epochs"]
                if "batch_size" in config_train:
                    train_config["batch_size"] = config_train["batch_size"]
                if "num_hops" in config_train:
                    train_config["num_hops"] = config_train["num_hops"]
                if "neighbor_size" in config_train:
                    train_config["neighbor_size"] = config_train["neighbor_size"]
                if "eval_interval" in config_train:
                    train_config["eval_interval"] = config_train["eval_interval"]
                if "early_stopping_patience" in config_train:
                    train_config["early_stopping_patience"] = config_train["early_stopping_patience"]
                if "checkpoint_interval" in config_train:
                    train_config["checkpoint_interval"] = config_train["checkpoint_interval"]
                if "device" in config_train:
                    train_config["device"] = config_train["device"]
                if "lambda_feat" in config_train:
                    train_config["lambda_feat"] = config_train["lambda_feat"]
                if "lambda_struct" in config_train:
                    train_config["lambda_struct"] = config_train["lambda_struct"]
                if "lambda_contrast" in config_train:
                    train_config["lambda_contrast"] = config_train["lambda_contrast"]
        
        logger.info(f"Training ISNE model with {train_config['epochs']} epochs on {self.device}...")
        
        # Train the model
        if self.trainer is None:
            raise ValueError("Trainer has not been initialized. Call _prepare_trainer first.")
            
        train_stats = self.trainer.train(
            features=graph_data.x,
            edge_index=graph_data.edge_index,
            epochs=train_config["epochs"],
            batch_size=train_config["batch_size"],
            num_hops=train_config["num_hops"],
            neighbor_size=train_config["neighbor_size"],
            eval_interval=train_config["eval_interval"],
            early_stopping_patience=train_config["early_stopping_patience"],
            verbose=True
        )
        
        # Update training metrics
        # Record training metrics
        self.training_metrics["end_time"] = time.time()
        self.training_metrics["duration"] = self.training_metrics["end_time"] - self.training_metrics["start_time"]
        
        # Get data from training stats
        if isinstance(train_stats, dict) and "epochs" in train_stats:
            self.training_metrics["epochs"] = train_stats["epochs"]
        else:
            self.training_metrics["epochs"] = 0
            
        # Initialize losses dictionary with safe access
        losses_dict = {
            "total_loss": 0.0,
            "feature_loss": 0.0,
            "structural_loss": 0.0,
            "contrastive_loss": 0.0
        }
        
        # Safely update with values from train_stats if they exist
        if isinstance(train_stats, dict):
            if "total_loss" in train_stats:
                losses_dict["total_loss"] = train_stats["total_loss"]
            if "feature_loss" in train_stats:
                losses_dict["feature_loss"] = train_stats["feature_loss"]
            if "structural_loss" in train_stats:
                losses_dict["structural_loss"] = train_stats["structural_loss"]
            if "contrastive_loss" in train_stats:
                losses_dict["contrastive_loss"] = train_stats["contrastive_loss"]
                
        self.training_metrics["losses"] = losses_dict
        
        # Compute summary statistics to quickly gauge training quality
        loss_summary: Dict[str, Dict[str, float]] = {}
        for key, series in self.training_metrics["losses"].items():
            if series:
                loss_summary[key] = {
                    "final": float(series[-1]),
                    "min": float(min(series)),
                    "avg": float(sum(series) / len(series))
                }
        self.training_metrics["loss_summary"] = loss_summary
        
        # Get model naming configuration with safer dictionary access
        # Default values
        name_prefix = "isne_model"
        version = "v1"
        use_timestamp = True
        keep_previous = True
        
        # Try to get values from configuration if available
        if hasattr(self.config, "isne"):
            isne_config = getattr(self.config, "isne")
            if isinstance(isne_config, dict) and "model" in isne_config:
                model_config = isne_config["model"]
                if isinstance(model_config, dict):
                    # Update with configuration values if they exist
                    if "name_prefix" in model_config:
                        name_prefix = model_config["name_prefix"]
                    if "version" in model_config:
                        version = model_config["version"]
                    if "use_timestamp" in model_config:
                        use_timestamp = model_config["use_timestamp"]
                    if "keep_previous_versions" in model_config:
                        keep_previous = model_config["keep_previous_versions"]
        
        # Create model filename
        if use_timestamp:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            model_filename = f"{name_prefix}_{version}_{timestamp}.pt"
        else:
            model_filename = f"{name_prefix}_{version}.pt"
            
        # Save the trained model
        if self.trainer is None:
            raise ValueError("Trainer has not been initialized. Call _prepare_trainer first.")
            
        # Call save_model which doesn't return a value
        self.trainer.save_model(self.model_output_dir / model_filename)
        model_save_path = str(self.model_output_dir / model_filename)
        logger.info(f"Model saved to: {model_save_path}")
        
        # Save a symlink to the latest model
        latest_model_path = self.model_output_dir / f"{name_prefix}_latest.pt"
        if latest_model_path.exists():
            latest_model_path.unlink()
        latest_model_path.symlink_to(model_filename)
        
        # Get document embeddings from trained model
        if self.trainer is None:
            raise ValueError("Trainer has not been initialized. Call _prepare_trainer first.")
        
        # Store graph data for later reference
        self.graph_data = graph_data
            
        embeddings = self.trainer.get_embeddings(graph_data.x, graph_data.edge_index)
        
        # Save training results
        results_path = self.output_dir / "training_results.json"
        with open(results_path, "w") as f:
            json.dump({
                "training_metrics": self.training_metrics,
                "config": getattr(self.config, "isne", {})["training"],
                "model_path": str(model_save_path),
                "pipeline_stats": pipeline_stats,
                "loss_summary": self.training_metrics["loss_summary"]
            }, f, indent=2)
        
        logger.info(f"ISNE training completed in {self.training_metrics['duration']:.2f} seconds")
        logger.info(f"Trained for {self.training_metrics['epochs']} epochs")
        logger.info(f"Model saved to {model_save_path}")
        logger.info(f"Training results saved to {results_path}")
        
        # Log quick metrics for human readability
        if 'total_loss' in self.training_metrics["loss_summary"]:
            logger.info(
                f"Total loss -> final: {self.training_metrics['loss_summary']['total_loss']['final']:.4f}, "
                f"min: {self.training_metrics['loss_summary']['total_loss']['min']:.4f}, "
                f"avg: {self.training_metrics['loss_summary']['total_loss']['avg']:.4f}")
        
        return self.training_metrics
    
    def generate_report(self, training_stats: Optional[Dict[str, Any]] = None, pipeline_stats: Optional[Dict[str, Any]] = None, model_path: Optional[str] = None) -> str:
        """
        Generate a report based on the training statistics.
        
        Args:
            training_stats: Training statistics dictionary
            pipeline_stats: Pipeline statistics dictionary
            model_path: Path to the trained model
        
        Returns:
            Report string
        """
        report = ""
        
        if training_stats:
            report += "Training Statistics:\n"
            report += f"  Epochs: {training_stats['epochs']}\n"
            report += f"  Duration: {training_stats['duration']:.2f} seconds\n"
            report += f"  Loss Summary:\n"
            for key, value in training_stats["loss_summary"].items():
                report += f"    {key}: final={value['final']:.4f}, min={value['min']:.4f}, avg={value['avg']:.4f}\n"
        
        if pipeline_stats:
            report += "\nPipeline Statistics:\n"
            report += f"  Total Files: {pipeline_stats['total_files']}\n"
            report += f"  Processing Time: {pipeline_stats['processing_time']}\n"
            report += f"  File Details: {pipeline_stats['file_details']}\n"
        
        if model_path:
            report += f"\nModel Path: {model_path}\n"
        
        return report
    
    def save_report(self, report_text: str, filename: str = "isne_training_report.txt") -> Path:
        """
        Save the report to a file.
        
        Args:
            report_text: Report string
            filename: Filename for the report
        
        Returns:
            Path to the saved report file
        """
        report_path = self.output_dir / filename
        with open(report_path, "w") as f:
            f.write(report_text)
        
        return report_path
    
    def collect_document_stats(self, documents: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Collect statistics about the documents.
        
        Args:
            documents: List of documents
        
        Returns:
            Dictionary with document statistics
        """
        stats = {}
        
        # Collect chunk statistics
        chunk_stats = {}
        for doc in documents:
            for chunk in getattr(doc, "chunks", []) if hasattr(doc, "chunks") else []:
                chunk_id = chunk["id"]
                chunk_stats[chunk_id] = {
                    "embedding_dim": len(chunk["embedding"]),
                    "text": getattr(chunk, "text", "") if hasattr(chunk, "text") else ""
                }
        
        stats["chunk_stats"] = chunk_stats
        
        # Collect document statistics
        doc_stats = {}
        for doc in documents:
            doc_id = doc["file_id"]
            chunks = getattr(doc, "chunks", []) if hasattr(doc, "chunks") else []
            doc_stats[doc_id] = {
                "num_chunks": len(chunks),
                "chunk_ids": [chunk["id"] for chunk in chunks]
            }
        
        stats["doc_stats"] = doc_stats
        
        return stats
    
    def add_node_features(self, doc_id: str, features: np.ndarray) -> None:
        """
        Add node features to the graph.
        
        Args:
            doc_id: Document ID
            features: Node features
        """
        if self.graph_data is None:
            raise ValueError("Graph data has not been initialized. Run train() first.")
            
        # Get the node index for the document
        if not hasattr(self.graph_data, 'node_ids'):
            raise AttributeError("Graph data has no 'node_ids' attribute")
            
        node_index = self.graph_data.node_ids.index(doc_id)
        
        # Add the features to the node
        if not hasattr(self.graph_data, 'x'):
            raise AttributeError("Graph data has no 'x' attribute")
            
        self.graph_data.x[node_index] = torch.tensor(features, dtype=torch.float)
    
    def plot_loss_components(self, output_filename: Optional[str] = None) -> Optional[str]:
        """
        Plot the loss components over training epochs.
        
        Args:
            output_filename: Optional filename to save the plot
            
        Returns:
            Path to the saved plot file, or None if not saved
        """
        # Implementation would go here
        return None

    def plot_training_progress(self, output_filename: Optional[str] = None) -> Optional[str]:
        """
        Plot the training progress metrics.
        
        Args:
            output_filename: Optional filename to save the plot
            
        Returns:
            Path to the saved plot file, or None if not saved
        """
        import matplotlib.pyplot as plt
        import os

        # Assuming self.training_metrics is a dictionary with training metrics
        training_metrics = self.training_metrics

        # Create a figure and axis
        fig, ax = plt.subplots()

        # Plot each training metric
        for metric, values in training_metrics.items():
            if metric != "loss_components":
                ax.plot(values, label=metric)

        # Set title and labels
        ax.set_title("Training Progress Metrics")
        ax.set_xlabel("Epoch")
        ax.set_ylabel("Value")

        # Legend
        ax.legend()

        # Save the plot if output_filename is provided
        if output_filename:
            output_dir = os.path.dirname(output_filename)
            if not os.path.exists(output_dir):
                os.makedirs(output_dir)
            plt.savefig(output_filename)
            return output_filename

        # Show the plot if output_filename is not provided
        plt.show()
        return None

    @classmethod
    def load_model(cls, model_path: Optional[str] = None) -> Union[ISNEModel, nn.Module]:
        """
        Load a trained ISNEModel from the specified path.
        
        Args:
            model_path: Path to the model file to load. If None, uses the latest model.
        
        Returns:
            Loaded ISNEModel instance or a compatible proxy model that implements the nn.Module interface
        """
        if model_path is None:
            model_dir = Path("./models/isne")
            model_files = list(model_dir.glob("isne_model_v*.pt"))
            if not model_files:
                raise FileNotFoundError("No ISNE model files found in the default directory")
            
            model_path_obj = max(model_files, key=lambda p: int(p.stem.split("_v")[1]))
            model_path = str(model_path_obj)
        
        # Safely load the model - handle both state dict and full model approaches
        try:
            # Try a direct load with weights_only=True (safer)
            loaded_data = torch.load(model_path, weights_only=True)
            
            # Check if we have a state dictionary format (from create_test_isne_model.py)
            if isinstance(loaded_data, dict) and 'isne_test_model' in loaded_data:
                logger.info("Detected test ISNE model state dictionary")
                
                # Create a simple proxy model that mimics ISNE behavior
                class ISNEModelProxy(nn.Module):
                    def __init__(self, state_dict: Dict[str, Any]) -> None:
                        super().__init__()
                        self.state_dict_data = state_dict
                        embed_dim = state_dict['embedding_dim']
                        
                        # Create the same architecture that we saved weights for
                        self.layer1 = nn.Linear(embed_dim, embed_dim * 2)
                        self.layer2 = nn.Linear(embed_dim * 2, embed_dim)
                        
                        # Load the weights
                        weights = state_dict['weights']
                        self.layer1.weight.data = weights['layer1.weight']
                        self.layer1.bias.data = weights['layer1.bias']
                        self.layer2.weight.data = weights['layer2.weight']
                        self.layer2.bias.data = weights['layer2.bias']
                    
                    def forward(self, x: torch.Tensor, edge_index: Optional[torch.Tensor]=None, edge_attr: Optional[torch.Tensor]=None, batch: Optional[torch.Tensor]=None) -> torch.Tensor:
                        # Apply a simplified version of the model's forward pass
                        x = torch.relu(self.layer1(x))
                        return torch.tanh(self.layer2(x))
                
                # Return our proxy model with the loaded weights
                model = ISNEModelProxy(loaded_data)
                return model
            else:
                # Regular model, just return it after properly typing it
                from src.isne.models.isne_model import ISNEModel
                return cast(ISNEModel, loaded_data)
                
        except RuntimeError as e:
            # If that fails, try with full pickle loading (less safe)
            if "Weights only load failed" in str(e):
                logger.warning("Weights-only loading failed, attempting full model loading")
                try:
                    # Try with weights_only=False
                    model = torch.load(model_path, weights_only=False)
                    return model
                except Exception as e2:
                    logger.error(f"Error loading model with weights_only=False: {e2}")
                    raise e2
            else:
                logger.error(f"Error loading model: {e}")
                raise e


def main() -> None:
    """
    Main function for running the ISNE training pipeline from command line.
    """
    parser = argparse.ArgumentParser(description="ISNE Training Orchestrator")
    parser.add_argument('--input-dir', type=str, default=None,
                        help='Directory containing processed documents from the pipeline')
    parser.add_argument('--output-dir', type=str, default=None,
                        help='Directory for storing training artifacts and results')
    parser.add_argument('--model-output-dir', type=str, default=None,
                        help='Directory for saving trained models')
    parser.add_argument('--epochs', type=int, default=None,
                        help='Number of training epochs')
    parser.add_argument('--learning-rate', type=float, default=None,
                        help='Learning rate for training')
    parser.add_argument('--hidden-dim', type=int, default=None,
                        help='Hidden dimension size for ISNE model')
    parser.add_argument('--device', type=str, default=None,
                        help='Device to use for training (e.g., "cpu", "cuda:0")')
    
    args = parser.parse_args()
    
    # Prepare configuration override
    config_override: Dict[str, Dict[str, Any]] = {"training": {}}
    if args.epochs is not None:
        config_override["training"]["epochs"] = args.epochs
    if args.learning_rate is not None:
        config_override["training"]["learning_rate"] = args.learning_rate
    if args.hidden_dim is not None:
        config_override["training"]["hidden_dim"] = args.hidden_dim
    
    # Initialize orchestrator with file-based approach for CLI usage
    # (documents parameter is None, so it will load from input_dir)
    orchestrator = ISNETrainingOrchestrator(
        documents=None,  # When called from CLI, use file-based approach
        input_dir=args.input_dir,
        output_dir=args.output_dir,
        model_output_dir=args.model_output_dir,
        config_override=config_override if config_override["training"] else None,
        device=args.device
    )
    
    # Run training
    orchestrator.train()


if __name__ == "__main__":
    main()
